server:
  port: 80
logging:
  level:
    root: warn
    ai.bitflow.bitwise.wallet: debug
  pattern:
    console: "[%clr(%d{M.d HH:mm:ss}){cyan}] %clr(${LOG_LEVEL_PATTERN}) %msg%n"

# derby example
# spring.datasource.url=jdbc:derby:crypto;create=true;
# spring.datasource.driverClassName=org.apache.derby.jdbc.AutoloadedDriver
spring:
  application:
    name: bitwise-wallet
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/bitwise?autoReconnect=true&amp;useUnicode=true&amp;charaterEncoding=utf-8
    username: root
    password: "!@Hy98657020"
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.mariadb.jdbc.Driver
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false

app:
  setting:
    symbol: btc
    testnet: true
    rpcUrl: http://bitflow.ai:50000/wallet/
    rpcId: btc-user
    rpcPw: btc-passwd
    decimals: 8
    blockStartFrom: 1569000
    minConfirm: 3
    pp: 00000000
    testAddress: 333qWatuDDtHRfJjgVcsVNAVvAwCQ114iR
    coldAddress:
    minAmtGather: 0.1
    minGasAmt: 0
    userAccount: btc-users
    ownerAccount: btc-owner
    ownerAddress: 3P6yoEDNrcZcUs3uMM3RW7qCGFtz8SZbk6
  useKafka: false
  useFcm: false