logging:
  level:
    root: warn
    ai.bitflow.bitwise.wallet: debug
  pattern:
    console: "[%clr(%d{M.d HH:mm:ss}){cyan}] %clr(${LOG_LEVEL_PATTERN}) %msg%n"

# spring.datasource.url=jdbc:derby:crypto;create=true;
# spring.datasource.driverClassName=org.apache.derby.jdbc.AutoloadedDriver

# JPA / HIBERNATE
server:
  port: 80
spring:
#  profiles:
#    include: blockchain
  application:
    name: bitwise-wallet
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/bitwise?autoReconnect=true&amp;useUnicode=true&amp;charaterEncoding=utf-8
    username: root
    password: "!@Hy98657020"
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.mariadb.jdbc.Driver
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false



app:
  useKafka: false
  useFcm: false
  crypto:
    symbol: btc
    testnet: true
    rpcUrl: http://bitflow.ai:50000/wallet/
    rpcId: btc-user
    rpcPw: btc-passwd
    decimals: 8
    blockStartFrom: 1569000
    minConfirm: 3
    userAccount: btc-users
    pp: 00000000
    testAddress: 333qWatuDDtHRfJjgVcsVNAVvAwCQ114iR
    ownerAccount: btc-owner
    ownerAddress: 3P6yoEDNrcZcUs3uMM3RW7qCGFtz8SZbk6
    coldAddress:
    minAmtGather: 0.1
    minGasAmt: 0

  blockchain:
    btc:
      homepage: https://bitcoin.org
      mainnet:
        port: 8332
        explorer_main: https://live.blockcypher.com/btc
        explorer_tx: https://live.blockcypher.com/btc/tx/
        faucet:
      testnet:
        port: 18332
        explorer_main: https://live.blockcypher.com/btc-testnet
        explorer_tx: https://live.blockcypher.com/btc-testnet/tx/
        faucet: https://testnet-faucet.mempool.co
    ltc:
      homepage: https://litecoin.org
      mainnet:
        port: 9333
        explorer_main: https://live.blockcypher.com/ltc
        explorer_tx: https://live.blockcypher.com/ltc/tx/
        faucet:
      testnet:
        port: 19335
        explorer_main: https://blockexplorer.one/litecoin/testnet
        explorer_tx: https://blockexplorer.one/litecoin/testnet/tx/
        faucet: http://testnet.litecointools.com
    bch:
      homepage: https://www.bitcoinabc.org
      mainnet:
        port: 8333
        explorer_main: https://explorer.bitcoin.com/bch
        explorer_tx: https://explorer.bitcoin.com/bch/tx/
        faucet:
      testnet:
        port: 18333
        explorer_main: https://explorer.bitcoin.com/tbch
        explorer_tx: https://explorer.bitcoin.com/tbch/tx/
        faucet: https://developer.bitcoin.com/faucets/bch
    bsv:
      homepage: https://bitcoinsv.io
      mainnet:
        port: 8333
        explorer_main: https://bchsvexplorer.com
        explorer_tx: https://bchsvexplorer.com/tx/
        faucet:
      testnet:
        port: 18333
        explorer_main: https://testnet.bitcoincloud.net
        explorer_tx: https://testnet.bitcoincloud.net/tx/
        faucet: https://faucet.bitcoincloud.net
    doge:
      homepage: https://dogecoin.com
      mainnet:
        port: 8333
        explorer_main: https://dogechain.info
        explorer_tx: https://dogechain.info/tx/
        faucet:
      testnet:
        port: 18333
        explorer_main: https://chain.so/testnet/doge
        explorer_tx: https://chain.so/tx/DOGETEST/
        faucet: https://doge-faucet-testnet.ggcorp.fr
    btg:
      homepage: https://bitcoingold.org
      mainnet:
        port: 8333
        explorer_main: https://explorer.bitcoingold.org/insight
        explorer_tx: https://explorer.bitcoingold.org/insight/tx/
        faucet:
      testnet:
        port: 18333
        explorer_main: https://test-explorer.bitcoingold.org/insight
        explorer_tx: https://test-explorer.bitcoingold.org/insight/tx/
        faucet: https://test-faucet.bitcoingold.org
    bcd:
      homepage: https://www.bitcoindiamond.org
      mainnet:
        port: 8333
        explorer_main: http://explorer.btcd.io
        explorer_tx: http://explorer.btcd.io/#/tx?tx=
        faucet:
      testnet:
        port: 18333
        explorer_main:
        explorer_tx:
        faucet: